# Generated by Django 4.0.6 on 2022-07-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='contect',
            new_name='content',
        ),
    ]
